sources:
  - symbol: BTCUSDT
    interval: 1m
    start_year: 2025
    start_month: 1
    end_year: 2025
    end_month: 12
  - symbol: ETHUSDT
    interval: 1m
    start_year: 2025
    start_month: 1
    end_year: 2025
    end_month: 12
  - symbol: BNBUSDT
    interval: 1m
    start_year: 2025
    start_month: 1
    end_year: 2025
    end_month: 12
paths:
  landing_dir: data/landing
  raw_output: data/raw
  refined_output: data/refined
  curated_output: data/curated
  quality_output: data/quality
spark:
  app_name: crypto-data-lakehouse
  master: "local[*]"
  driver_memory: 4g
  shuffle_partitions: "16"
